### ISSUE TITLE
This colorscheme does not work with highlightedyank plugin by default

### ISSUE THREAD

**Issue by jdhao** [ErichDonGubler/vim-sublime-monokai#9] opened 2019-01-10 10:10 UTC
I use [vim-highlightedyank](https://github.com/machakann/vim-highlightedyank) to show the text I have yanked. But unfortunately, this colorscheme does not work vim-highlightedyank out of box. See more discussions [here](https://github.com/machakann/vim-highlightedyank/issues/36). 

It would be great if this plugin support highlighted yank out of box.

**Comment by ErichDonGubler** [comment] 2019-06-22 13:26
Sorry for taking so long to get back here -- this fell under my radar.

So, I would be more than happy to resolve this. I THINK it might already be resolved with the resolution to https://github.com/ErichDonGubler/vim-sublime-monokai/issues/10 -- if you pull the latest `master` of this repo and remove the config you used to patch this, does it still work?

**Comment by jdhao** [comment] 2019-06-25 11:05
Thanks, it works now. No hacks are needed.

**Comment by ErichDonGubler** [comment] 2019-06-25 14:02
Woot! I'm glad the issue is fixed. Closing. :slightly_smiling_face:

**Closed as completed by ErichDonGubler** 2019-06-25 14:02 UTC
Labels: bug
